baseurl = "http://colindcarroll.com/"
title = "Colin Carroll"
copyright = "&copy; 2017 Colin Carroll"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  name = "Colin Carroll"
  role = "Software Engineer"
  organization = "Kensho"
  avatar = "me.jpg"
  email = ">>> \"{user}@{provider}.com\".format(user=colcarroll, provider=gmail)"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Enable native social sharing buttons?
  sharing = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/colindcarroll"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/ColCarroll"

  [[params.social]]
    icon = "file-text"
    icon_pack = "fa"
    link = "//dl.dropboxusercontent.com/u/28589453/resume/resume.pdf"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Thoughts"
  url = "#posts"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 2

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 3

[[menu.main]]
  name = "About"
  url = "#about"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 5

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
